# Generated by Django 5.2.7 on 2025-10-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("domain", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("start_date", models.DateTimeField(auto_now_add=True)),
                ("due_date", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ON_GOING", "On Going"),
                            ("COMPLETED", "Completed"),
                            ("DUE", "Due"),
                        ],
                        default="ON_GOING",
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
