# Generated by Django 5.2.7 on 2025-10-17 12:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_project_created_at_alter_project_due_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="modules",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="project",
            name="priority",
            field=models.CharField(
                choices=[
                    ("ON_GOING", "On Going"),
                    ("COMPLETED", "Completed"),
                    ("DUE", "Due"),
                ],
                default="LOW",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="progress",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="tasks",
            field=models.IntegerField(default=0),
        ),
    ]
