# Generated by Django 5.2.7 on 2025-10-18 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_project_modules_project_priority_project_progress_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="priority",
            field=models.CharField(
                choices=[
                    ("TO DO", "To Do"),
                    ("ON_GOING", "On Going"),
                    ("COMPLETED", "Completed"),
                    ("DUE", "Due"),
                ],
                default="LOW",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("TO DO", "To Do"),
                    ("ON_GOING", "On Going"),
                    ("COMPLETED", "Completed"),
                    ("DUE", "Due"),
                ],
                default="TO DO",
                max_length=20,
            ),
        ),
    ]
