# Generated by Django 5.2.7 on 2025-10-18 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_alter_project_priority_alter_project_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="priority",
            field=models.CharField(
                choices=[("LOW", "Low"), ("MEDIUM", "Medium"), ("HIGH", "High")],
                default="LOW",
                max_length=20,
            ),
        ),
    ]
