# Generated by Django 5.2.7 on 2025-10-18 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_alter_project_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="SRS",
            field=models.FileField(blank=True, null=True, upload_to="srs/"),
        ),
    ]
