# Generated by Django 5.2.7 on 2025-11-08 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_client_project_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='no_of_hours',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
